In [233]:
#falta definir el tema de periodos

In [1]:
from dbconn import querydb, querydbtopandas 
import numpy as np
import pandas as pd

In [243]:
pd.set_option('display.max_columns', 500)

In [318]:
#esto solo tiene en cuenta febrero 
mayor = "2019-03"
menor = "2019-02"

In [341]:
df = querydbtopandas(f"""select    a11.id_pres_prestacion  id_pres_prestacion,

                max(a17.desc_pres_prestacion)  desc_pres_prestacion,

                max(a17.prestac_pres_prestacion)  prestac_pres_prestacion,

                a11.id_nom_nomenclador  id_nom_nomenclador,

                a11.id_pre_prestador  id_pre_prestador,

                max(a15.desc_pre_nombre)  desc_pre_nombre,

                max(a15.vigente)  vigente,

                a12.id_pre_prestador  id_pre_prestador0,

                max(a16.desc_pre_nombre)  desc_pre_nombre0,

                sum(a11.i_ft_importe_prestacion)  RDENES,

                sum(case  when (  i_ft_importe_prestacion *i_Ft_Cantidad <= 0) then 0  when  (i_ft_importe_prestacion *i_Ft_Cantidad <> 0 ) then   i_Ft_Cantidad   end )  CANTIDADORDENES0

from      DBA.ft_ordenes               a11

                join        DBA.d_auto_autorizacion     a12

                  on        (((a11.id_auto_sucursal * 10000000) + a11.i_ft_autorizacion) = ((a12.id_auto_sucursal * 10000000) + a12.id_auto_autorizacion))

                join        DBA.d_exp_expediente a13

                  on        (((a11.id_ofi_oficina * 10000000) + a11.id_exp_expediente) = ((a13.ofi * 10000000) + a13.id_exp_expediente))

                join        DBA.fecha_mes a14

                  on        (a13.exp_mes = a14.exp_mes)

                join        DBA.d_pre_prestador   a15

                  on        (a11.id_pre_prestador = a15.id_pre_prestador)

                join        DBA.d_pre_prestador_autoriza a16

                  on        (a12.id_pre_prestador = a16.id_pre_prestador)

                join        DBA.d_pres_prestacion a17

                  on        (a11.id_pres_prestacion = a17.id_pres_prestacion)

where (CONVERT(DATETIME,a13.exp_mes, "mm-YYYY") >= date("{menor}") and CONVERT(DATETIME,a13.exp_mes, "mm-YYYY") < date("{mayor}")

and a15.id_pre_tipo in ('E','P')

and a11.id_nom_nomenclador in (1,11)

and (not a11.id_pre_prestador in (154688)))

group by             a11.id_pres_prestacion,

                a11.id_nom_nomenclador,

                a11.id_pre_prestador,

                a12.id_pre_prestador""")

In [342]:
df

,id_pres_prestacion,desc_pres_prestacion,prestac_pres_prestacion,id_nom_nomenclador,id_pre_prestador,desc_pre_nombre,vigente,id_pre_prestador0,desc_pre_nombre0,RDENES,CANTIDADORDENES0
0,48,Descompresión del mediano a nivel del túnel ca...,010505,1,26559,"Petraglia Ramos,Guillermo L.",A,1539,Sanatorio Mater Dei,1846.67,1.0
1,76,"Blefaroplastía -injerto, cantoplastía, trasopl...",020202,1,56921,"Sereday,Carlos",A,182730,CLINICA ZABALA,5559.43,1.0
2,79,"Escisión de lesión de párpados, blefarectomía ...",020205,1,44665,"Ghilino,Oscar D.",A,44665,"Ghilino,Oscar D.",2531.04,1.0
3,81,Escision de lesion conjuntiva -quiste epitelio...,020302,1,56921,"Sereday,Carlos",A,56921,"Sereday,Carlos",3123.62,1.0
4,81,Escision de lesion conjuntiva -quiste epitelio...,020302,1,80593,"Lavalle Paniza,Alfredo J.",A,80593,"Lavalle Paniza,Alfredo J.",4938.08,1.0
...,...,...,...,...,...,...,...,...,...,...,...
1799,35833,Cirugía de Cadera con prótesis de Banco.,12172619,11,20203,"Copquin,Alberto D.",A,99785,SANATORIO DE LOS ARCOS,7678.24,1.0
1800,35833,Cirugía de Cadera con prótesis de Banco.,12172619,11,144974,"Sayago,Gustavo A.",A,0,Sin Asignar,7678.24,1.0
1801,35833,Cirugía de Cadera con prótesis de Banco.,12172619,11,144974,"Sayago,Gustavo A.",A,99785,SANATORIO DE LOS ARCOS,30712.96,4.0
1802,36102,Masto plastia reductora Post Cirugía de la Obe...,13021146,11,20199,"Sokolowicz,Daniel",A,1763,CLINICA Y MATERNIDAD SUIZO ARGENTINA,21971.65,1.0
1803,49040,Mastoplastía post extracción,13021200,11,160824,"Angheben,Eduardo",A,99785,SANATORIO DE LOS ARCOS,48288.96,2.0

In [343]:
df = df[df["id_pre_prestador0"] != 0]

In [344]:
len(df)

1499

In [345]:
cirujias_validas = pd.read_csv("cx_evaluar.csv",dtype=str, header=None)

In [346]:
cirujias_validas = cirujias_validas[0].tolist()

In [347]:
df["prestac_pres_prestacion"] = df["prestac_pres_prestacion"].str.strip()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [348]:
df = df[df["prestac_pres_prestacion"].isin(cirujias_validas_str)]

In [349]:
centros_propios = [1632,1763,
2086,26564,31244,55060,64677,75470,78363,85316,85401,99785,118209,122803,135464,182730,187243,196559,196561,201019,206939,210252,211421,213729,217747,226756,235779,240895]

In [350]:
df_propios = df[df["id_pre_prestador0"].isin(centros_propios)]

In [351]:
df_no_propios = df[~df["id_pre_prestador0"].isin(centros_propios)]

In [352]:
propios = df_propios.groupby(["id_pre_prestador", "desc_pre_nombre"])["CANTIDADORDENES0"].sum().reset_index().rename(columns = {"CANTIDADORDENES0": "propios"})

In [353]:
no_propios = df_no_propios.groupby(["id_pre_prestador", "desc_pre_nombre"])["CANTIDADORDENES0"].sum().reset_index().rename(columns = {"CANTIDADORDENES0": "no_propios"})

In [354]:
final = pd.merge(propios, no_propios,how="outer")

In [355]:
final.fillna(0,inplace=True)

In [356]:
final["total"]  = final["propios"] + final["no_propios"]

In [357]:
final["porcentaje en propios"] = (final["propios"] /final["total"])

In [358]:
final = final.round()

In [359]:
final.rename(columns= {"id_pre_prestador": "Prestador", "desc_pre_nombre": "Razón Social", "propios": "Propias", "no_propios": "No propias", "total": "Total general","porcentaje en propios":"% en Propias" },inplace=True)

In [360]:
final

,Prestador,Razón Social,Propias,No propias,Total general,% en Propias
0,172,"Pasqualini,Rodolfo S.",12.0,2.0,14.0,1.0
1,193,"Ferro,Paula C.",1.0,0.0,1.0,1.0
2,423,"Pérez Macri,Silvia C.",4.0,0.0,4.0,1.0
3,438,"Ortega Traverso,Jorge A.",3.0,0.0,3.0,1.0
4,509,"Montesinos,Manuel R.",1.0,0.0,1.0,1.0
...,...,...,...,...,...,...
547,205475,"Martins,Andrea E.",0.0,2.0,2.0,0.0
548,205825,"Veglia,María Florencia",0.0,2.0,2.0,0.0
549,209138,"Perea Ansinelli,Alexis G.",0.0,4.0,4.0,0.0
550,211271,"Lucarelli,Pablo",0.0,4.0,4.0,0.0
551,225746,"Moreno,Claudia P.",0.0,1.0,1.0,0.0

In [230]:
final_50_febrebro  = final.head(50)

In [232]:
final_50_febrebro.to_excel("final_febrero_50_prestadores_mas_a_verificar_final_final.xlsx")

In [291]:
pd.read_excel("final_febrero_50_prestadores_mas_a_verificar_final_final.xlsx")

,Unnamed: 0,Prestador,Razón Social,Propias,No propias,Total general,% en Propias
0,0,172,"Pasqualini,Rodolfo S.",12,2,14,0.857143
1,1,193,"Ferro,Paula C.",1,0,1,1.000000
2,2,423,"Pérez Macri,Silvia C.",4,0,4,1.000000
3,3,438,"Ortega Traverso,Jorge A.",3,0,3,1.000000
4,4,509,"Montesinos,Manuel R.",1,0,1,1.000000
5,5,624,"Trepat,Ana M.",2,0,2,1.000000
6,6,625,"Muñiz,Alcira A.",1,0,1,1.000000
7,7,632,"Lavarello,Marcelo",2,0,2,1.000000
8,8,715,"Bistoletti,Pedro H.",2,0,2,1.000000
9,9,744,"Vigliocco,Guillermo",7,0,7,1.000000
10,10,754,"Saez,Martín A.",12,0,12,1.000000
11,11,759,"Butler,Santiago",2,1,3,0.666667
12,12,761,"Lanari Zubiaur,Felipe J.",4,0,4,1.000000
13,13,790,"Duncan,Diego",8,0,8,1.000000
14,14,20203,"Copquin,Alberto D.",7,0,7,1.000000
15,15,20219,"Devesa,Néstor R.",9,0,9,1.000000
16,16,20245,"Pece,Orlando F.",21,0,21,1.000000
17,17,20246,"Monti,Fernando A.",19,0,19,1.000000
18,18,20250,"Wigutov,Gabriel N.",22,0,22,1.000000
19,19,20258,"García Aguirre,Ernesto J.",1,0,1,1.000000
20,20,20564,"Nespral,Edgardo J.",19,0,19,1.000000
21,21,20565,"Menéndez,José A.",17,0,17,1.000000
22,22,20621,"Raijman,Miguel A.",4,0,4,1.000000
23,23,20630,"Cantisani,Rafael",5,0,5,1.000000
24,24,20671,"Cassella,Ricardo N.",1,0,1,1.000000
25,25,20681,"Daniele,Antonio R.",2,0,2,1.000000
26,26,20692,"Rodríguez Vidal,Dora",2,0,2,1.000000
27,27,20696,"Yahni,Roberto C.",2,0,2,1.000000
28,28,20700,"Silberman,Fernando",1,1,2,0.500000
29,29,20708,"Dal Verme,Aníbal E.",5,7,12,0.416667
30,30,20710,"Slafer,Mariana L.",3,0,3,1.000000
31,31,20772,"Faure,Pablo H.",5,0,5,1.000000
32,32,20775,"Katz,Renato M.",15,0,15,1.000000
33,33,20780,"Martire,Adolfo L.",1,0,1,1.000000
34,34,20788,"Katz,Alberto E.",2,0,2,1.000000
35,35,20805,"Scorticati,Carlos H.",2,0,2,1.000000
36,36,20822,"Paniceres,Guillermo H.",1,0,1,1.000000
37,37,20831,"Giménez,Mariano E.",32,1,33,0.969697
38,38,21411,"Katz,Gustavo R.",2,0,2,1.000000
39,39,21432,"Bendersky,David",6,0,6,1.000000
40,40,21434,"Taddei,Andrés M.",22,1,23,0.956522
41,41,21446,"Cerviño,Oscar A.",5,0,5,1.000000
42,42,21447,"Ramanzin,Víctor G.",3,0,3,1.000000
43,43,21478,"Heinen,Fernando L.",4,5,9,0.444444
44,44,21661,"Chaulet,Arístides",4,0,4,1.000000
45,45,21694,"Esquivel Molla,Enrique E.",1,0,1,1.000000
46,46,21779,"Sousa Martínez,Fermín",2,0,2,1.000000
47,47,21887,"Nassif,Juan C.",5,0,5,1.000000
48,48,21897,"Spira,Diego S.",2,0,2,1.000000
49,49,21908,"Winograd,Raúl H.",1,0,1,1.000000